### PR TITLE
update packaging to build wheel & source dist for PyPI uploads

### LINKED ISSUE #114: update packaging to build wheel & source distribution
Update the packaging per [PEP518](https://peps.python.org/pep-0518/) so that `python -m build --sdist --wheel --outdir dist .` will build the requisite files for upload to PyPI.

One of the things to correct is the dependencies here which belong in a different section:
https://github.com/BCDA-APS/mdaviz/blob/d6e04896d3f8f73fa0a8d7a171861ed058b6522b/pyproject.toml#L5
https://github.com/BCDA-APS/mdaviz/blob/d6e04896d3f8f73fa0a8d7a171861ed058b6522b/pyproject.toml#L8

See the comparable section in [gemviz](https://github.com/BCDA-APS/gemviz/blob/23429156276dcbaf289aac527de9fbf8cfe8f285/pyproject.toml#L52-L56):

```ini
dependencies = [
  "matplotlib",
  "pyRestTable",
  "tiled",
]
```

Additional suggestions are in the [Python Packaging User Guide](https://packaging.python.org/en/latest/).

### PR DESCRIPTION
**Pull request by prjemian**
- close #114

### CODE REVIEW

**Comment by prjemian** [comment]
This PR is in draft mode pending the requirement of the [`synApps-mdalib`](https://github.com/BCDA-APS/mdaviz/issues/114#issuecomment-2074044095) dependency.

**Comment by prjemian** [comment]
Wait on #117

**Comment by prjemian** [comment]
Wait for:

- #119
- #117

Required for:

- #113

**Comment by prjemian** [comment]
- #117 

Packaging updated and source mdalib code has been _vendored_ here.  @rodolakis , ready for review.

**Review by rodolakis — APPROVED** [review]
LGTM

**Pull request merged**
