### PR TITLE
vendor the mdalib code

### LINKED ISSUE #117: Add the mdalib source code
An alternative to creating a wheel of the mdalib for PyPI is to _vendor_ the files into this package.  Considering years could pass between `mdalib` updates, vendoring might be the better approach.  There are just two files, 9kB and 51kB.

```
-rw-rw-r-- 1 prjemian prjemian 9.1K Sep  2  2022 f_xdrlib.py
-rw-rw-r-- 1 prjemian prjemian  56K Sep  2  2022 mda.py
```

Also note that PyPI already has packages for [`mda`](https://pypi.org/project/mda/) (analysis of molecular dynamics simulations) and [`mdalib`](https://pypi.org/project/mdalib/) (kafka, telephony?).  If the synApps `mdalib` package is to be uploaded, it might take the name `synApps-mdalib`.

_Originally posted by @prjemian in https://github.com/BCDA-APS/mdaviz/issues/114#issuecomment-2074044095_

### PR DESCRIPTION
**Pull request by prjemian**
- close #117

### CODE REVIEW

**Comment by prjemian** [comment]
https://github.com/EPICS-synApps/support/issues/34

**Comment by prjemian** [comment]
@rodolakis This is ready for review.

@timmmooney: Your comments are welcome.

**Comment by timmmooney** [comment]
I don't understand the purpose of uncommenting the f_xdrlib stuff. f_xdrlib still relies on xdrlib, which I understand to be the problem. However, I don't object to anyone trying to improve this code. I'm glad for it.

Tim Mooney ***@***.***) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by prjemian** [comment]
@timmmooney -- Thanks for the reply.

https://github.com/BCDA-APS/mdaviz/blob/15847e8af7f8453e86a3a0ae713b12eb84440f6b/mdaviz/synApps_mdalib/f_xdrlib.py#L27

This is the only reference to `xdrlib` in `f_xdrlib.py` that I can find.  (And, `xdrlib` is not imported at this point.)  So, I assumed `f_xdrlib` had replaced all necessary code provided by the `xdrlib` package.  If that is not the case, then we can reference an open-source alternative.

**Comment by prjemian** [comment]
I swapped the try..except block to prefer xdrlib.  Starting with Py3.13 release, the code will use local `f_xdrlib` unless xdrlib is provided by a thrid-party package.

https://github.com/BCDA-APS/mdaviz/blob/15847e8af7f8453e86a3a0ae713b12eb84440f6b/mdaviz/synApps_mdalib/mda.py#L18-L23

**Comment by timmmooney** [comment]
My bad.  I forgot how it worked. Your solution seems the best way to go.

Tim Mooney ***@***.***) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Review by rodolakis — APPROVED** [review]
If Tim is happy I am happy. 
In general LGTM.

**Pull request merged**
